# vim ft=yaml

# Notes below compliments of the scikit-image team:

# - Use http://yaml-online-parser.appspot.com/ to make sure the yaml
#   file is valid.  http://lint.travis-ci.org/ is recommended
#   elsewhere but does not give helpful error reports.

# - Make sure all of your "-" lines start on the same column

# - Use bash scripts for `before_install` and `script` or any part
#   that has conditional statements
#    - Make sure they are "executable" (chmod +x)
#    - Use the following header:

#    ```
#      #!/usr/bin/env bash
#      set -ex
#    ```

# - Use the `retry` bash function from `before_install.sh` before a
#   command to have it try 3 times before failing.

# - Use `pip install --retries N` for retrying package downloads.

# - Use the `section` function to start a folded section of the
#   script.  Section names must have underscores or dots instead of
#   spaces and must be accompanied by a corresponding `section_end`
#   call.

# - Feel free to cancel a build rather than waiting for it to go to
#   completion if you have made a change to that branch.

# - A VM with 64bit Ubuntu 12.04 is a huge help for debugging.


language: python
#dist: trusty
sudo: false
cache:
  # See http://docs.travis-ci.com/user/caching/#pip-cache
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/sphinx
    - $HOME/.cache/matplotlib
    - $HOME/.ccache
    - $HOME/.local
addons:
  apt:
    packages:
    - ccache
    - wget
    - fontconfig
    - libfreetype6-dev
    - libxft-dev
    - libhdf5-serial-dev
    - libnetcdf-dev

env:
  global:
    - secure: "Fsx12sYNJG2MCvy1wPhYQOlOXTp9sUCqeD19P4h0hl7Cx7/URqOXzGbYG/fSBjQOVYiICuiEHH4Ln6Eo6+hSGRzbshb1J+dvDGA7BAiGo4l5RQwZDr/2vzFZSFqZeR3DcV9OchTCVKBLUqY309Yu0WyjX0H3KjQA1GLWVqulEtY="

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8ac07e795c3e4024f522
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

matrix:
  include:
    - python: 2.7
      env:
        - SKIP_DOCS=1
    - python: 3.4
    - python: 3.5
      env: 
        - COVERAGE=1
        - DEPLOY_DOCS=1

before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - which python; python --version
  - source .drone/travis_funcs.sh

install:
  - .drone/travis_install.sh

script: .drone/travis_script.sh

after_success: 
  - .drone/deploy_docs.sh
  - pip install codecov
  - codecov